### ISSUE TITLE
some things to add to make the cheat better :)

### ISSUE THREAD

**Issue by omarloler** [smefcc/smefs-Indigo-Remastered#65]
left hand knife / fix sniper cross hair / make the aimbot more smoother / unload button ( turn of the cheat ) / backwards legit aa.          thx btw the cheat is very good :)

**Comment by Jozkah** [comment]
Since people are mentally disabled nowadays , left hand knife = bind 3 "slot3; cl_righthand 0;" , just bind all other 1 2 4 5 to "slotNUMBER; cl_righthand 1;" also bind q to the q button + cl_righthand; 
Backwards legit aa is useless to be honest sorry , you can fix sniper crosshair it just takes 10 seconds.

**Comment by sigge200** [comment]
Cant you check if you are holding ur knife in the cheat and Then use that command? Would make life easier.
